version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: uap-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: uap-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - uap-network

volumes:
  mongodb_data:
    driver: local

networks:
  uap-network:
    driver: bridge
